package com.chrissytopher.socialmedia

const val USERNAME_KEY = "USERNAME"
const val EMAIL_KEY = "EMAIL"
const val ACCOUNT_KEYPAIR_KEY = "ACCOUNT_KEYPAIR"
const val ACCOUNT_CERTIFICATE_KEY = "ACCOUNT_CERTIFICATE"

const val SETTING_FORMAT_KEY = "SETTING_FORMAT"
const val LIKE_ICON_KEY = "LIKE_ICON"
const val QUAG_KEY = "QUAG"
const val ROMANTICAL_KEY = "ROMANTICAL"
const val DARK_MODE_KEY = "DARK_MODE"

const val ICON_PIC_STRING = "ACCOUNT_ICON_PICTURE_STRING"
const val ICON_X_PER = "ACCOUNT_ICON_CROP_XVALUE"
const val ICON_Y_PER = "ACCOUNT_ICON_CROP_YVALUE"
const val ICON_SCALE = "ACCOUNT_ICON_SCALE"
const val ICON_OUTPUT = "ACCOUNT_ICON_DEFAULT_OUTPUT_SIZE"

const val CROP_OFFSETX = "CROPPING PAGE X OFFSET"
const val CROP_OFFSETY = "CROPPING PAGE Y OFFSET"
const val CROP_SIZE="CROPPING PAGE SIZE"
